// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseContainer: typeof import('./components/BaseContainer.vue')['default']
    BaseSpinner: typeof import('./components/BaseSpinner.vue')['default']
    BaseSuspense: typeof import('./components/BaseSuspense.vue')['default']
    IHeroiconsOutlineAnnotation: typeof import('~icons/heroicons-outline/annotation')['default']
    IHeroiconsOutlineBriefcase: typeof import('~icons/heroicons-outline/briefcase')['default']
    IHeroiconsOutlineChat: typeof import('~icons/heroicons-outline/chat')['default']
    IHeroiconsOutlineEye: typeof import('~icons/heroicons-outline/eye')['default']
    IHeroiconsOutlineFire: typeof import('~icons/heroicons-outline/fire')['default']
    IHeroiconsOutlineHome: typeof import('~icons/heroicons-outline/home')['default']
    IHeroiconsOutlineMoon: typeof import('~icons/heroicons-outline/moon')['default']
    IHeroiconsOutlineNewspaper: typeof import('~icons/heroicons-outline/newspaper')['default']
    IHeroiconsOutlineStar: typeof import('~icons/heroicons-outline/star')['default']
    IHeroiconsOutlineSun: typeof import('~icons/heroicons-outline/sun')['default']
    IHeroiconsSolidArrowRight: typeof import('~icons/heroicons-solid/arrow-right')['default']
    IHeroiconsSolidExternalLink: typeof import('~icons/heroicons-solid/external-link')['default']
    ItemList: typeof import('./components/ItemList/Index.vue')['default']
    ItemListItem: typeof import('./components/ItemList/Item.vue')['default']
    ItemView: typeof import('./components/ItemView/Index.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    StoryList: typeof import('./components/StoryList/Index.vue')['default']
    StoryListItem: typeof import('./components/StoryList/Item.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheTabbar: typeof import('./components/TheTabbar.vue')['default']
  }
}

export { }
